Prevent possible flickering of `ScrollView` content in Firefox
react-ui-org/react-ui pull request #133
Opened 2020-07-20 22:01 UTC by adamkudrna

2020-09-03 07:36 UTC, bedrich-schindler requested changes

2020-09-10 15:19 UTC, adamkudrna commented on package.json
> +  "version": "0.33.1",
This all was originally a fix for the potential bug that happened to me couple of times but suddenly disappeared. I will get back to it and probably close it.

2020-09-11 09:10 UTC, bedrich-schindler approved these changes

2020-09-18 09:56 UTC, adamkudrna commented
It doesn't seem to be any problem of this kind in Firefox.

> If it ain't broken, don't fix it.

2020-09-18 09:56 UTC, closed without merging