Remove bottom margin from last-child elements (#180)
react-ui-org/react-ui pull request #259
Opened 2021-03-31 16:57 UTC by adamkudrna

Separate shared bottom spacings into categories with configurable values.

New theming options:

- `--rui-spacing-bottom-default`
- `--rui-spacing-bottom-headings`
- `--rui-spacing-bottom-layouts`

Closes #180.

2021-04-01 06:58 UTC, bedrich-schindler requested changes
It seems logic to me, but when I tried to change those values using Chrome DevTools, only spacing of headings changed. Spacing of elements did not - for example for Toolbar, there is no visual change when I change all values to `--rui-spacing-6` or `1`:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/10213870/113255680-65904400-92c8-11eb-8cb4-d6970655b07a.png">

Can you check it?

2021-04-08 15:45 UTC, adamkudrna commented
@bedrich-schindler I think you did the test in docs context, correct? There is a default spacing around all direct descendants (`> *`) provided by live playground which is probably what you encountered. This spacing is useful most of the times and when you switch it off in dev tools you'll see it works:

<img width="1666" alt="Snímek obrazovky 2021-04-08 v 17 39 43" src="https://user-images.githubusercontent.com/5614085/114056606-2185dc00-9892-11eb-8b24-ce05c1288fdb.png">

2021-04-08 17:54 UTC, adamkudrna commented
@bedrich-schindler … or just head to any configurable component example like [this one](http://localhost:3000/components/layout/toolbar#alignment). Multiple sibling layouts are used there and I just added a few more.

2021-04-09 07:31 UTC, bedrich-schindler commented
Ok, if it does not work in playground, it is ok then. We might write some note that some of those modification do not work in playground, so user knows that it is not a bug. But it is for another discussion. Maybe new issue ..

2021-04-12 21:25 UTC, adamkudrna commented
> Ok, if it does not work in playground, it is ok then. We might write some note that some of those modification do not work in playground, so user knows that it is not a bug. But it is for another discussion. Maybe new issue ..

You're right, I appended a note to Foundation > Spacing:

![image](https://user-images.githubusercontent.com/5614085/114464601-42c62f80-9be6-11eb-95bf-39d9ed0e8aed.png)

2021-04-15 20:47 UTC, merged