Leverage CSS cascade layers to fix and user-proof styles order
react-ui-org/react-ui pull request #529
Opened 2024-03-06 21:24 UTC by adamkudrna

As long as `layers.scss` (layers order definition) is called first, our Sass styles can be imported in any order.

It solves the incorrect (but unavoidable, due to the way we compile CSS) call order of styles in our `index.js`.

Also, developers can now extend the CSS cascade instead of just prepending or appending their styles to ours.

For example:

```css
/* My custom app styles */
@layer foundation.elements {
  code {
    background-color: silver;
  }
}
```

Closes #518.

2024-03-08 11:24 UTC, bedrich-schindler commented
Just wow!

2024-03-08 19:54 UTC, adamkudrna commented on src/layers.scss
> +@layer theme, foundation, helpers, components, utilities;
I realized the component styles are currently unlayered, thus ordered as last (after the `utilities` layer). It seems this is what I need to do with all component classes:

```css
.root {
    @layer components.checkboxField {
        /* root styles */
    }
}
```

2024-03-09 05:06 UTC, mbohal approved these changes

2024-03-11 09:51 UTC, dacerondrej approved these changes

2024-03-19 09:27 UTC, bedrich-schindler commented
For some reason, Table` is not working in this branch.`master` is OK.

![image](https://github.com/react-ui-org/react-ui/assets/10213870/6d6a8f8b-018e-48b4-8e13-f5d1d01c1863)

2024-03-19 09:28 UTC, bedrich-schindler requested changes
For some reason, Table is not working in this branch. `master` is OK.

![313993940-02e712c7-4a77-4e3b-9039-2f0858c252bd](https://github.com/react-ui-org/react-ui/assets/10213870/ae5369f2-1ef0-4c5f-9217-aaec7d376912)

2024-03-25 17:18 UTC, adamkudrna commented
> For some reason, Table is not working in this branch. `master` is OK.

Fixed, I forgot to rename nested TableCell styles.

2024-03-27 13:16 UTC, bedrich-schindler approved these changes

2024-03-27 14:50 UTC, merged