Change `label` of inputs to accept any node (#526)
react-ui-org/react-ui pull request #543
Opened 2024-05-30 09:07 UTC by bedrich-schindler

Closes #526

2024-05-30 09:11 UTC, bedrich-schindler commented
Documentation does not specifically mention data type of labels, only in the props table.  @adamkudrna @mbohal @dacerondrej, do you think we need to extend documentation of those components to mention this possibility or not? Personally, I do not see any additional value to this.

I expect to extend documentation of Popover to mention possibility to extend label with Popover (https://github.com/react-ui-org/react-ui/issues/489), but do not know what to say about it in documentation of inputs ...

2024-06-03 08:17 UTC, mbohal requested changes

2024-06-03 08:17 UTC, mbohal commented on src/components/CheckboxField/CheckboxField.jsx
I think we also need to add support for the `InputGroup` component.

2024-06-03 08:17 UTC, mbohal commented on src/components/CheckboxField/CheckboxField.jsx
I think we should document this with code examples.

2024-06-03 09:47 UTC, mbohal commented on src/components/CheckboxField/CheckboxField.jsx
I checked and I think the `InputGroup` is the only one, where we want to include it.

Other components mostly render `label` "within" something (e.g. `Badge`, `Button`). Then there is `TextLink` where the name kind of implies text prop.

2024-06-06 05:41 UTC, bedrich-schindler commented on src/components/CheckboxField/CheckboxField.jsx
Please check my comment: https://github.com/react-ui-org/react-ui/pull/543#issuecomment-2139112900

Personally, I don't think so we need to show examples of everything we support. End user must know React, so he/she must know what React.Node means and therefore I do not see any reason to have it as example. What more, I think user should use always except situations when he/she needs to provide additional info about the field. I can imagine to extend prop documentation or general guidelines with something like "Use text labels unless it is necessary to wrap text label into Popover-like to  component to provide additional info about the field". 

There was separate issue for that I guess but I think it disappeared from the board after Monday's meeting.

What do you think @mbohal @adamkudrna @dacerondrej

2024-06-12 09:13 UTC, dacerondrej approved these changes

2024-06-12 09:39 UTC, mbohal commented on src/components/CheckboxField/CheckboxField.jsx
Ok, lets put it in general guidelines

2024-06-17 16:47 UTC, adamkudrna commented on src/components/FileInputField/FileInputField.jsx
> +   * File input field label.
Thanks!

2024-07-31 16:18 UTC, adamkudrna approved these changes

2024-07-31 16:28 UTC, merged