Fix layout context prop resolving for boolean types (#567)
react-ui-org/react-ui pull request #568
Opened 2024-09-17 08:05 UTC by atmelmicro

Allows boolean props to propagate when layout context is false

Closes #567

2024-09-17 11:48 UTC, mbohal requested changes

2024-09-17 11:48 UTC, mbohal commented on src/components/_helpers/resolveContextOrProp.js
> +  if (contextValue === false) {
Could you please rewrite it so there are only two returns?

```
if (…) {
  return a;
}

return b;
```

Having three returns makes it hard to follow the flow of the code. I know this function is short, but still…

2024-10-07 09:27 UTC, adamkudrna commented on src/components/_helpers/resolveContextOrProp.js
Does it make any sense to have a test for it? Possibly with an example similar to that in the original issue #567.

2024-10-08 12:17 UTC, mbohal commented on src/components/_helpers/resolveContextOrProp.js
I think Ill leave it up to @atmelmicro to decide.

It is one simple condition, so I think that maybe just a comment would work:

```js
// We need to test:
//  * `false` - for when the `contextValue` is boolean
//  * `null` - for when the `contextValue` is non-boolean
if (contextValue === false || contextValue === null) {
```

However test would communicate it just as good and it would test it on top.

I have no preference, really, but I agree with @adamkudrna that one or the other should be added.

2024-10-23 13:07 UTC, atmelmicro commented on src/components/_helpers/resolveContextOrProp.js
In my opinion the comment is more descriptive, it describes the why, not just how it should work.

2024-10-23 14:25 UTC, mbohal approved these changes

2024-11-21 10:46 UTC, bedrich-schindler approved these changes

2024-11-26 08:24 UTC, merged