Fix misplaced  when using Floating UI (#566)
react-ui-org/react-ui pull request #576
Opened 2024-11-19 09:15 UTC by atmelmicro

2024-11-19 11:17 UTC, mbohal approved these changes
:+1:

2024-11-21 10:43 UTC, bedrich-schindler requested changes
In the end, after Monday's discussion, I do not see this solution satisfying. 

Floating UI is just example we use just because Floating UI is currently trending library that solves positioning. But we are open to every implementation user decides to use. This means that we are unable to determine attributes user would need to pass, position, x, y are attributes that are necessary for our example but might not be for production use.

I want @adamkudrna to decide this together with us. I would personally suggest to implement something like `style`. I would call it e.g. `placementStyle`.

`placementStyle` could be either just the way how to bypass styles (`style={placementStyle}`) or it can have black or white list or style attributes to pass.

I know that React 19 will get rid of `forwardRef`, but I see this concept of forward-ref (respectively forward-styles) useful as we can control it for the component we know it use useful. 

This is my proposal.

I can also imagine that we would require to pass either `placement` or `placementStyle`, so that only one can be set at the time. But this is just question arising in my head.

2024-11-21 13:53 UTC, mbohal commented
> But we are open to every implementation user decides to use.

I agree with @bedrich-schindler that we do not want to embrace Floating UI to closely.

I think the question is if some other placement implementation is likely to express position differently then `x`, `y` and `position`. I don't feel versed enough in CSS to decide this. I would think it less likely, but I'm don't really know.

> I can also imagine that we would require to pass either placement or placementStyle, so that only one can be set at the time. But this is just question arising in my head.

So you mean to have one new prop:

```
placement: PropTypes.shape({
    /**
   * This sets the CSS property `position` of the popover. This is reserved for use with Floating UI.
   */
  position: PropTypes.string,
  /**
   * This sets the CSS property `top` of the popover. This is reserved for use with Floating UI.
   */
  x: PropTypes.string,
  /**
   * This sets the CSS property `left` of the popover. This is reserved for use with Floating UI.
   */
  y: PropTypes.string,
})
```

so we can then easily switch between placement formats?

2024-11-29 10:06 UTC, adamkudrna commented
- I can imagine positioning solved via CSS transforms (`translateX`, `translateY` properties). I think the new drag-and-drop library we use does it this way as it is more performant and fluent.
- Can we have something like adapters for supported positioning libraries? We would provide the Floating UI adapter and anyone could plug-in their own.

2024-11-30 06:31 UTC, mbohal commented
> Can we have something like adapters for supported positioning libraries? We would provide the Floating UI adapter and anyone could plug-in their own.

So something like:

```
getPlacement: PropTypes.func,
```

where the signature of Floating UI implementation would be:
```
getPlacement(x: number, y: number, position: string): string
```

with the return value being the style HTML attribute value?
I like that.

2024-12-02 13:08 UTC, mbohal commented
On call we agreed that the best solution is from @bedrich-schindler

> placementStyle could be either just the way how to bypass styles (style={placementStyle}) or it can have black or white list or style attributes to pass.

We would like to filter the style attributes to allow all properties that are neede for:

* absolute positioning
* CSS transform

We need to reflect this in the docs.

2024-12-02 13:54 UTC, adamkudrna commented
In case a general positioning white-list of relevant CSS properties is needed, this is what I can think of:

```
position
inset
inset-inline-start
inset-inline-end
inset-block-start
inset-block-end
top
right
bottom
left
translate
transform-origin
```

Notes (could be mentioned in the docs):

- ⚠️ `inset` is a shorthand for `top right bottom left`, not for `inset-*` properties.
- as opposed to `top right bottom left` and the `inset` shorthand, `inset-*` properties are writing-direction aware.

https://developer.mozilla.org/en-US/docs/Web/CSS/inset

I am leaving out these:

- `inset-inline`, `inset-block`: if a shorthand is needed, I would go with `inset`.
- `transform`: it allows to set any transforms, not only x/y translation. That seems to be too powerful to me.

2024-12-20 06:30 UTC, mbohal requested changes

2024-12-20 06:30 UTC, mbohal commented on src/components/Popover/README.md
> +style you want to apply to the popover. This prop is filtered and should only
I think we should reword:

> This prop is filtered and should only …

to:

> This prop should only …

The code does not filter anything. It merely shows warning and error when in dev mode.  I find this sufficient, but the docs should match the code.

2024-12-20 06:30 UTC, mbohal commented on src/components/Popover/_helpers/cleanPlacementStyle.js
> +  if (process.env.NODE_ENV !== 'production') {
In dev mode the allowed styles are already handled by propType validation. I dont think we need this explicit check at all.

If we do, the errors in console caused by `bject.keys(placementStyle)` when `placementStyle === null` need to be fixed,

2025-01-22 20:32 UTC, adamkudrna reviewed
I tried to test it in the browser and the Floating UI example works, but the others above are all broken.

2025-01-22 20:32 UTC, adamkudrna commented on src/components/Popover/README.md
> +be used to position the popover. The allowed props are
```suggestion
be used to position the popover. The allowed props are:
```

2025-01-23 16:30 UTC, atmelmicro commented on src/components/Popover/_helpers/cleanPlacementStyle.js
> +  if (process.env.NODE_ENV !== 'production') {
The null fix is still needed because Object.entries(null) fails. I have implemented it like this. Not sure if this this the correct way

```jsx
style={cleanPlacementStyle(placementStyle ?? {})}
```

2025-01-27 12:23 UTC, adamkudrna approved these changes

2025-01-27 12:30 UTC, mbohal approved these changes

2025-01-30 13:58 UTC, mbohal commented on src/components/Popover/_helpers/cleanPlacementStyle.js
> +  if (process.env.NODE_ENV !== 'production') {
I would rather that in such we do not call the `cleanPlacementStyle` function at all. Maybe something like:

`{placementStyle ? (...cleanPlacementStyle(placementStyle)) : null}`

2025-01-31 16:17 UTC, bedrich-schindler approved these changes

2025-01-31 16:39 UTC, merged